import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
const read=name=>readFile(new URL('../'+name,import.meta.url),'utf8');
test('entrance has native sign-in navigation and a direct public demo',async()=>{const html=await read('login.html');assert.match(html,/href="\/signin-with-chatgpt\?return_to=\/account"/);assert.match(html,/href="\/workspace"/);assert.match(html,/not a reconstruction/);assert.doesNotMatch(html,/three\.module|scene\.js|\.glb/);assert.match(html,/data-provider="google" disabled/);assert.match(html,/data-provider="facebook" disabled/);});
test('login avoids the geometry payload and keeps bounded entry assets',async()=>{assert.ok((await stat(new URL('../assets/art/pixel-queue-v2.jpg',import.meta.url))).size<550000);assert.ok((await stat(new URL('../entrance.js',import.meta.url))).size<15000);const code=await read('entrance.js');assert.doesNotMatch(code,/fetch\(['"]\/signin-with-chatgpt/);assert.match(code,/AbortSignal.timeout/);const motion=await read('pixel.js');assert.match(motion,/prefers-reduced-motion/);assert.match(motion,/visibilitychange/);});
test('runner is tied to real model loading and supports reduced motion',async()=>{assert.match(await read('index.html'),/id="loading"[\s\S]*?class="runner"/);assert.match(await read('motion.css'),/prefers-reduced-motion/);assert.match(await read('engine.js'),/progressRunner.hidden=terminal.has/);});
test('all user-facing pages share the pixel theme without altering real output',async()=>{for(const file of ['login.html','account.html','logout.html','index.html','engine.html'])assert.match(await read(file),/href="\/?pixel.css"/);assert.match(await read('pixel.css'),/Silkscreen/);assert.doesNotMatch(await read('pixel.css'),/#scene\s*\{[^}]*filter:/);});
test('sign-out only claims completion after the account endpoint returns 401',async()=>{const code=await read('entrance.js');assert.match(code,/response.status===401[\s\S]*?SESSION CLOSED/);assert.match(code,/SESSION STILL ACTIVE/);assert.match(code,/STATUS UNAVAILABLE/);assert.match(code,/signout-with-chatgpt\?return_to=\/signed-out/);});
